# ------------------------------------------------------------------------------------
# BUTTON SETTINGS
# ------------------------------------------------------------------------------------
# 옵션 중 open-type 옵션은 아래의 타입 중 원하는 방식들을 골라 추가할 수 있습니다.
#  - SHIFT-F    : 웅크리기 + 아이템스왑
#  - ICON       : 아이템 우클릭 ( 인벤토리에 핫바에 고정됩니다. )
#  - COMMAND    : 명령어 입력
# ------------------------------------------------------------------------------------
default:
  # 서버에 적용 될 프리셋을 설정합니다. ( 인게임 명령어로도 가능합니다. )
  # /퀵메뉴 적용 <프리셋이름>
  preset: 기본 프리셋

  # 퀵 메뉴를 오픈 할 방식을 선택합니다.
  # 원하는 타입을 아래의 기본 설정과 같이 넣을 수 있습니다.
  # 원하지 않는 옵션이 있다면 지워주시면 됩니다.
  # 위의 설명을 참고해주세요.
  open-type: [SHIFT-F, ICON, COMMAND]

  icon:
    # open-type 이 아이콘 일 때, 아이콘으로 사용 될 아이템의 Minecraft-URL 입니다.
    # 아래와 같은 URL 값은 'https://minecraft-heads.com/custom-heads' 에서 찾을 수 있습니다.
    # 해당 사이트에서 가장 하단의 Minecraft-URL 칸의 Copy 버튼을 눌러 값을 붙여넣으면 됩니다.
    url: '123daf8c965e5034c4bfc79d2d6ee8339f3a08a7e62bc56b7ab8eb2d7d070'

    # 아이콘에 표시 될 이름입니다.
    display: '&6≪ &a&l빠른 메뉴 열기 &6≫'

    # 아이콘에 표시 될 로어입니다.
    lore:
      - '&7----------------------------'
      - ''
      - '&f 아이템을 손에 들고 우클릭을 하여,'
      - '&f &a&l&n빠른 메뉴&f를 열 수 있습니다.'
      - '&8 원하는 버튼을 왼클릭하여 선택합니다.'
      - ''
      - '&7----------------------------'

    # 아이콘이 표시 될 슬롯 번호입니다. ( 1 부터 9 까지 입력할 수 있습니다. )
    slot: 5

# ------------------------------------------------------------------------------------
# MESSAGE SETTINGS
# ------------------------------------------------------------------------------------
# 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# ------------------------------------------------------------------------------------
message:
  # 접두사
  prefix: '&9&l[ 퀵메뉴 ] &r'

  # 선택 된 버튼의 접두사
  selected-button-prefix: '&a&l[ &6'

  # 선택 된 버튼의 접미사
  selected-button-suffix: '&a&l ]'

  # 선택되지 않은 버튼의 접두사
  default-button-prefix: '&7'

  # 선택되지 않은 버튼의 접미사
  #default-button-suffix: ''

  # 실행 될 명령이 없는 버튼을 클릭했을 떄 출력되는 메세지
  none-command: '&7준비중인 버튼입니다.'

  # 시간초과로 인한 메세지
  time-out: '&c시간 초과로 인하여 메뉴를 닫습니다!'

  # 메뉴를 열고 이동하여 취소됐을 때 출력되는 메세지 ( 다른 블럭으로 이동하면 취소됩니다. )
  away-from-menu: '&c메뉴를 열고 이동하여 메뉴를 닫았습니다.'


