name: ST-QuickMenu
main: net.starly.qm.QuickMenu
author: Starly Team
website: http://starly.kr/discord

description: QuickMenu Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

permissions:
  net.starly.qm.command:
    description: 퀵메뉴 명령어 퍼미션
  net.starly.qm.use:
    description: 퀵메뉴 사용 퍼미션

commands:
  quick-menu:
    aliases: [qm, 퀵메뉴]